author: "AlexRogalskiy"
name: "gnakrydev notification"
description: "Push message to the Gnakrydev Mobile app"
branding:
  icon: "info"
  color: "yellow"
inputs:
  apiKey: # id of input
    description: "Who to greet"
    required: true
    default: "World"
  title: # organization secret
    description: "Secret defined at Org. level"
    required: true
  message: # organization secret
    description: "Secret defined at Org. level"
    required: true
  type: # organization secret
    description: "Secret defined at Org. level"
    default: "info"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "pypy3.9"
    - run: pip install https://github.com/GnakryDev/gnakrydev-cli/raw/main/release/gnakrydev-0.1.3-py3-none-any.whl --force-reinstall
      shell: bash
    - run: gnakrydev message --apikey $apiKey --title $title --content $message --type $type --id ${{ github.repository }}
      shell: bash

outputs:
  notification: # id of output
    description: "The time we greeted you"
    value: "message sent"
